### ISSUE TITLE
Sunset  rust_xmldeserialize 

### ISSUE THREAD

**Issue by rwxroot** [lendsmartlabs/rust_xmldeserialize#6]
This library is no longer being used in Lendsmart core_api. Please archive it or purge post this PR is merged and deployed in prod.

https://github.com/lendsmartlabs/core_api/pull/1274

**Comment by indykish** [comment]
@Armiixteryx  Can we review and approve by replying to this comment (since this is not a PR).

**Comment by Armiixteryx** [comment]
We can sunset sir. We don't use this crate anymore. Also, there are better alternatives to manage XML in Rust nowadays.

**Comment by indykish** [comment]
> We can sunset sir. We don't use this crate anymore. Also, there are better alternatives to manage XML in Rust nowadays.


Thanks David, Archiving.

**Comment by indykish** [comment]
Archived.
